set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

if(NOT DEFINED ARM_LINUX_GCC_COMPILER)
    set(ARM_LINUX_GCC_COMPILER "arm-linux-gnueabi-gcc")
endif()

set(CMAKE_C_COMPILER "${ARM_LINUX_GCC_COMPILER}" CACHE STRING "ARM Linux GCC compiler")
